# Generated by Django 4.1.1 on 2022-09-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='line',
            field=models.CharField(default='text-decoration-none', max_length=100),
        ),
    ]
